apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: httpserver
spec:
  gateways:
    - httpserver
  hosts:
    - cncamp-service.cncamp.io
  http:
    - match:
        - port: 80
      route:
        - destination:
            host: cncamp-service.module12.svc.cluster.local
            port:
              number: 8000
---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: httpserver
spec:
  selector:
    istio: ingressgateway
  servers:
    - hosts:
        - cncamp-service.cncamp.io
      port:
        name: http-default
        number: 80
        protocol: HTTP
