apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cncamp-server
  name: cncamp-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cncamp-server
  template:
    metadata:
      labels:
        app: cncamp-server
    spec:
      containers:
        - name: cncamp-server
          image: julianchu/cncamp-go-server:dev
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 3
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
          env:
              - name: VERSION
                valueFrom:
                    configMapKeyRef:
                        name: cncamp-configmap
                        key: version
          resources:
              requests:
                  memory: "64Mi"
                  cpu: "250m"
              limits:
                  memory: "128Mi"
                  cpu: "500m"

        # volumes:
        #     - name: config
        #       configMap:
        #           name: cncamp-configmap
        #           items:
        #           - key: "version"
        #             path: "version"

