apiVersion: v1
kind: Service
metadata:
  name: cncamp-service
spec:
    #type: NodePort
  selector:
    app: cncamp
  ports:
      #    - name: http
      #      port: 8000
      #      nodePort: 30950
      - port: 8000
